name: gerar-playlist

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Gerar playlist
        run: python gerar.py

      - name: Salvar playlist
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add playlist.m3u
          git commit -m "playlist atualizada" || echo "nada para salvar"
          git push
